// ============================================
// 💜 K-POP KOSMIC - BRAND CONFIGURATION 💜
// ============================================
// The Ultimate K-Pop Stan Reading Experience
// Stan culture × cosmic destiny × idol energy
// Copy this file to config.js to activate
// ============================================

var BRAND_CONFIG = {
    // ============================================
    // 🎤 BRAND IDENTITY
    // ============================================
    brandName: "K-pop Kosmic",
    tagline: "Your Idol Destiny Awaits, Stan 💜",
    subTagline: "65+ Readings • Your Complete Idol Blueprint • No Sign-Up • Always Free • 화이팅! ✨",
    
    // Who is this reading for?
    subjectType: "person",
    subjectLabel: "Stan",
    subjectLabelPlural: "Stans",
    
    // ============================================
    // 🫰 COPY & LANGUAGE (Full Stan Mode)
    // ============================================
    inputLabels: {
        name: "🎤 Your Stage Name",
        namePlaceholder: "Enter your name or dream stage name ✨",
        nameHelper: "What would your lightstick say? 💫",
        
        birthDate: "🎂 Your Debut Date (Birthday)",
        birthDateHelper: "The day you entered this era 🌟",
        
        birthTime: "⏰ Time of Debut",
        birthTimeHelper: "For accurate Rising Sign — ask your eomma! 🫰",
        
        birthPlace: "📍 Hometown",
        birthPlacePlaceholder: "Seoul, South Korea ✨",
        birthPlaceHelper: "Where your trainee arc began 🏠"
    },
    
    ctaButton: "🫰 Reveal My Idol Destiny 화이팅!",
    loadingMessage: "Calculating your idol blueprint… 🎤💜",
    
    // Result page copy
    resultTitle: "Your Idol Blueprint 💜",
    resultSubtitle: "The Cosmic Profile of",
    generatedBy: "Generated by K-pop Kosmic 💜 11:11 Make a Wish",
    
    // ============================================
    // 🌟 SECTION NAMES - Deep K-Pop Culture
    // ============================================
    sections: {
        celestial: {
            name: "🌟 Celestial Line-Up",
            icon: "🌟",
            description: "Your planetary positions — the cosmic members of your inner group 🫰"
        },
        numbers: {
            name: "🔢 Trainee Numbers",
            icon: "🔢",
            description: "The numerology behind your debut — every number tells your story 💫"
        },
        soul: {
            name: "✨ Debut Mission",
            icon: "✨",
            description: "Your deeper purpose — the concept only you can pull off 💜"
        },
        forecasts: {
            name: "🎤 Comeback Seasons",
            icon: "🎤",
            description: "Your upcoming eras — when to drop your next album 📀"
        },
        cycles: {
            name: "💫 Era Cycles",
            icon: "💫",
            description: "The evolving chapters of your idol journey — every era matters 🦋"
        }
    },
    
    // ============================================
    // 💜 READING TITLES - Full K-Pop Immersion
    // ============================================
    readingTitles: {
        sunSign: "☀️ Sun Sign — Your Main Vocal Energy",
        moonSign: "🌙 Moon Sign — Your Hidden B-Side",
        risingSign: "⭐ Rising Sign — Your Stage Presence",
        mercurySign: "💬 Mercury — Your V-Live Chat Style",
        venusSign: "💗 Venus — Your Visual & Love Language",
        marsSign: "🔥 Mars — Your Performance Fire",
        jupiterSign: "🌟 Jupiter — Your All-Kill Luck",
        saturnSign: "💪 Saturn — Your Trainee Struggle Arc",
        chineseZodiac: "🐉 Eastern Zodiac — Your Spirit Animal Line",
        moonPhase: "🌙 Birth Moon Phase — Your Pre-Debut Energy",
        
        lifePath: "🎤 Life Path — Your Idol Archetype",
        destiny: "✨ Destiny Number — Your Debut Concept",
        soulUrge: "💜 Soul Urge — Your True Bias Wrecker Energy",
        personality: "🫰 Personality Number — Your Fan Service Style",
        birthday: "🎂 Birthday Number — Your Special Hidden Talent",
        maturity: "👑 Maturity Number — Your Sunbaenim Era",
        
        personalYear: "📀 Current Comeback Energy",
        pinnacle: "🏆 Career Pinnacles — Your Daesang Moments",
        challenge: "💪 Growth Arc — Your Trainee Challenges",
        
        northNode: "🚀 North Node — Your Debut Direction",
        southNode: "🌸 South Node — Your Pre-Debut Gifts",
        lifeLesson: "💫 Core Idol Lesson — What Your Journey Teaches",
        
        yearAhead: "🔮 This Era's Forecast — What's Coming",
        firstYear: "🌟 Debut Year Energy — Your Opening Track"
    },
    
    // ============================================
    // 🎨 COLORS & STYLING - Neon K-Pop Aesthetic
    // ============================================
    colors: {
        primary: "#FF69B4",       // Hot pink (lightstick glow)
        secondary: "#A855F7",     // Vivid purple (concert ocean)
        accent: "#00FFFF",        // Neon cyan (stage laser)
        background: "#0f0520",    // Deep dark purple (concert venue)
        backgroundDark: "#080210",
        text: "#f0e6ff",
        textLight: "#ffffff",
        cardBg: "rgba(168,85,247,0.08)",
        cardBorder: "rgba(255,105,180,0.25)"
    },
    
    // ============================================
    // 🔤 FONTS (K-Pop Aesthetic)
    // ============================================
    fonts: {
        heading: "'Black Han Sans', 'Noto Sans KR', 'Impact', sans-serif",
        body: "'Noto Sans KR', 'Inter', 'Segoe UI', sans-serif",
        accent: "'Black Han Sans', 'Noto Sans KR', sans-serif"
    },
    
    // ============================================
    // 🌙 THEME
    // ============================================
    theme: "dark",
    
    // ============================================
    // ⚙️ FEATURES
    // ============================================
    features: {
        showBirthTime: true,
        showBirthPlace: true,
        showPDFDownload: true,
        showShareButtons: true,
        showTableOfContents: true,
        showProgressBar: true,
        requireBirthTime: false,
        requireBirthPlace: false
    },
    
    // ============================================
    // 📱 SOCIAL SHARING
    // ============================================
    sharing: {
        hashtags: ["KpopKosmic", "IdolDestiny", "StanLife", "KpopNumerology", "MyIdolBlueprint", "1111MakeAWish"],
        defaultMessage: "I just revealed my idol destiny! 🎤💜 My archetype is… 화이팅! ✨ #KpopKosmic",
        twitterHandle: "@kpopkosmic"
    },
    
    // ============================================
    // 💎 PREMIUM FEATURES
    // ============================================
    premium: {
        enabled: false,
        price: "$11.11",
        features: [
            "PDF Photocard Download 📸",
            "Ad-Free Stan Experience ✨",
            "Printable Idol Blueprint 🖨️",
            "Bias Compatibility Reading 💜"
        ]
    },
    
    // ============================================
    // 📝 FOOTER
    // ============================================
    footer: {
        copyright: "© 2026 K-pop Kosmic 💜 11:11 Make a Wish",
        disclaimer: "For entertainment purposes only — not affiliated with any K-pop agency, label, or artist. Stan responsibly! 사랑해 💜🫰",
        links: [
            { text: "Privacy Policy", url: "/privacy.html" },
            { text: "Terms of Service", url: "/terms.html" },
            { text: "Contact", url: "/contact.html" }
        ]
    },
    
    // ============================================
    // 🔍 SEO
    // ============================================
    seo: {
        title: "K-pop Kosmic 💜 Your Idol Destiny Revealed | K-Pop Astrology & Numerology",
        description: "Discover your K-pop idol archetype with 65+ free cosmic readings! Your stage presence, debut energy, bias-wrecker potential & idol blueprint. 화이팅! No sign-up needed.",
        keywords: "kpop numerology, kpop astrology, idol archetype, kpop personality test, stan destiny, kpop birth chart, idol energy, kpop kosmic, bias compatibility, kpop fortune, idol blueprint, lightstick energy"
    },

    // ============================================
    // 🎤 K-POP LOADING MESSAGES
    // ============================================
    loadingMessages: [
        "Scanning the stars for your debut date… 🌟",
        "Calculating your lightstick frequency… 💜",
        "Mapping your idol archetype constellation… ✨",
        "Analyzing your bias-wrecker potential… 🫰",
        "Decoding your comeback concept… 🎤",
        "Reading your trainee evaluation report… 💪",
        "Aligning your stage presence with the cosmos… 🔥",
        "Your fanchant is being written in the stars… 💫",
        "Checking your all-kill probability… 🏆",
        "Loading your concert ocean colors… 🌊💜"
    ],

    // ============================================
    // 💜 K-POP WELCOME FLOW
    // ============================================
    welcomeFlow: {
        headerTitle: "Welcome to K-pop Kosmic 💜",
        headerSubtitle: "Your idol destiny is about to be revealed… 🫰",
        
        step1: {
            title: "🎤 How This Works, Stan",
            body1: "Enter your birth details and we'll reveal the cosmic idol blueprint that was written in the stars the moment you debuted into this world.",
            body2: "You'll receive <strong>65+ personalized readings</strong> — your stage presence, debut concept, trainee arc, comeback energy, and so much more. Think of it as your cosmic audition results! 💜",
            highlight: "\"At the exact moment you were born, the universe dropped your debut single — and we're about to play it back for you.\" 🎵"
        },
        step2: {
            title: "🎨 Choose Your Concept",
            description: "Every idol has a concept. Choose the energy that fits your vibe:",
            pinkLabel: "Girl Group",
            purpleLabel: "K-Pop",
            blueLabel: "Boy Group",
            pinkDesc: "<strong>Girl Group</strong> — Soft, powerful feminine energy. Think BLACKPINK meets cosmic destiny. 🩷",
            purpleDesc: "<strong>K-Pop</strong> — Universal idol energy. Balanced and versatile. 💜",
            blueDesc: "<strong>Boy Group</strong> — Bold, grounded masculine energy. Think BTS meets the universe. 💙",
            note: "You can switch concepts anytime from the bar at the top 🔄"
        },
        step3: {
            title: "📖 No Rush — This Is Your Album",
            body1: "This reading is like a full album, not a single track. <strong>65+ tracks of cosmic insight</strong> — take your time with each one.",
            body2: "Some tracks will hit immediately. Others are slow burns that reveal their meaning over time. Come back whenever you need guidance — your album is always here. 💜",
            highlight: "\"Treat this like your favorite album — revisit it, discover new details, let it grow with you.\" 🎵",
            savedNote: "<strong>Your readings auto-save like a playlist.</strong> Create readings for your bias, your bestie, your whole group — they'll all be waiting in your library. 📚"
        },
        step4: {
            title: "🌟 A Note on Accuracy",
            body1: "About <strong>70% will feel like a personal fancam</strong> — eerily accurate and just for you. The rest? The stars capture your full potential, not your whole story.",
            body2: "If something doesn't hit, maybe it's your unreleased track — hidden potential waiting for the right comeback. Or maybe it's just not your concept. Either way, 화이팅! 💪",
            highlight: "\"Maybe this is the reading that reveals the idol you were always meant to be.\" ✨",
            privacyNote: "<strong>Your data stays on your device.</strong> We never see, collect, or share your birth details. Your privacy is more protected than a sasaeng-proof dorm. 🔒"
        }
    },

    // ============================================
    // 💫 OPENING LETTER (Results Page)
    // ============================================
    openingLetter: {
        title: "Your Complete Idol Blueprint 💜",
        paragraphs: [
            "At the exact moment you were born, the universe composed a debut single that has never been performed before and will never be performed again. 🎵",
            "This reading decodes that cosmic composition — your stage presence, your hidden B-sides, your comeback energy, and the trainee arc that shaped your soul. Think of it as your official cosmic evaluation from the universe's entertainment agency. 💜",
            "Take your time exploring each track on this album. Some insights will hit like your favorite song on first listen; others are slow burns that reveal their magic over months. This is your idol blueprint — a lifelong guide, not a quick fan-edit. 화이팅! ✨"
        ],
        note: "If any birth details are wrong, tap \"New Reading\" to re-audition with the right info. 🎤"
    },

    // ============================================
    // 🌟 BIG THREE LABELS
    // ============================================
    bigThree: {
        header: "Your Idol Snapshot 🫰",
        subheader: "The Big Three — your core idol identity 💜",
        sun: { label: "Sun Sign", desc: "Main Vocal Energy ☀️" },
        moon: { label: "Moon Sign", desc: "Hidden B-Side 🌙" },
        rising: { label: "Rising Sign", desc: "Stage Presence ⭐" }
    },

    // ============================================
    // 🤖 AI GUIDE — STAR
    // ============================================
    ai: {
        // OpenRouter model to use (free tier)
        model: 'openrouter/healer-alpha',

        // ⚠️  OWNER ACTION REQUIRED:
        // Paste your OpenRouter API key below (free tier).
        // This key will be visible in client-side JS — only use
        // a free-tier key with a spending cap set in OpenRouter.
        // Users can also supply their own key via the ⚙️ button.
        siteKey: '',

        // Daily request limit per visitor (when using the site key)
        dailyLimit: 10,

        // AI persona details
        personaName: 'STAR',
        personaTitle: 'Cosmic Idol Guide from 2087',

        // OpenRouter API endpoint (OpenAI-compatible)
        endpoint: 'https://openrouter.ai/api/v1/chat/completions'
    }
};

// ─── Expose AI config to ai-guide.js ───
if (typeof window !== 'undefined') {
    window.KK_CONFIG = window.KK_CONFIG || {};
    window.KK_CONFIG.ai = BRAND_CONFIG.ai;
}

const BRAND_PRESETS = {
    kpop: BRAND_CONFIG
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { BRAND_CONFIG, BRAND_PRESETS };
}